WITH CAR30 AS (
    SELECT C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE*30*(1-P.DISCOUNT_RATE/100), 0) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON C.CAR_TYPE = P.CAR_TYPE
    WHERE C.CAR_TYPE IN ('세단', 'SUV') AND P.DURATION_TYPE = '30일 이상'
)

SELECT C.CAR_ID, C.CAR_TYPE, C.FEE
FROM CAR30 C
WHERE C.FEE >= 500000 AND C.FEE < 2000000 AND C.CAR_ID IN 
(
    SELECT H1.CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H1
    WHERE H1.CAR_ID NOT IN (SELECT DISTINCT H2.CAR_ID
                        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H2
                        WHERE H2.START_DATE <= '2022-11-30' AND H2.END_DATE >= '2022-11-01')

)
ORDER BY C.FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC