SELECT 
    C1.CAR_ID,
    IF(SUM(
        CASE WHEN '2022-10-16' 
        BETWEEN C1.START_DATE AND C1.END_DATE > 0 THEN 1 ELSE 0 
        END) > 0, '대여중', '대여 가능') AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C1
GROUP BY C1.CAR_ID
ORDER BY C1.CAR_ID DESC