-- FIRST_HALF : FLAVOR가 기본 키, SHIPMENT_ID를 외래 키
-- JULY : SHIPMENT_ID가 기본 키, FLAVOR를 외래 키

SELECT J_FLAVOR AS FLAVOR
FROM (
    (SELECT F.FLAVOR AS F_FLAVOR, SUM(F.TOTAL_ORDER) AS F_TOTAL_ORDER
    FROM FIRST_HALF F
    GROUP BY F.FLAVOR) AS FF
    INNER JOIN
    (SELECT J.FLAVOR AS J_FLAVOR, SUM(J.TOTAL_ORDER) AS J_TOTAL_ORDER
    FROM JULY J
    GROUP BY J.FLAVOR) AS JJ
    ON FF.F_FLAVOR = JJ.J_FLAVOR
)
ORDER BY FF.F_TOTAL_ORDER + JJ.J_TOTAL_ORDER DESC
LIMIT 3
