-- 코드를 입력하세요
SELECT MONTH(M1.START_DATE) AS MONTH, M1.CAR_ID, COUNT(M1.HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY M1
WHERE (MONTH(M1.START_DATE) IN ('8', '9', '10')) AND (YEAR(M1.START_DATE) = '2022')
                    AND M1.CAR_ID IN (SELECT M2.CAR_ID
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY M2
                    WHERE (MONTH(M2.START_DATE) IN ('8', '9', '10')) AND (YEAR(M2.START_DATE) = '2022')
                    GROUP BY M2.CAR_ID
                    HAVING COUNT(M2.HISTORY_ID) >= 5)
GROUP BY MONTH, M1.CAR_ID
ORDER BY MONTH ASC, M1.CAR_ID DESC

